/**
 * CDK Infrastructure Tests
 *
 * These tests verify that the CloudFormation template generated by CDK
 * contains the expected resources with correct configurations.
 */

import * as cdk from 'aws-cdk-lib';
import * as fs from 'fs';
import * as path from 'path';
import { SecureFileDropStack } from '../lib/secure-file-drop-stack';
import { RETENTION_DAYS } from '../shared';

// Ensure frontend/dist exists for BucketDeployment during tests
const frontendDistPath = path.join(__dirname, '..', 'frontend', 'dist');
const frontendDistIndexPath = path.join(frontendDistPath, 'index.html');

beforeAll(() => {
  // Create minimal frontend/dist for tests if it doesn't exist
  if (!fs.existsSync(frontendDistPath)) {
    fs.mkdirSync(frontendDistPath, { recursive: true });
  }
  if (!fs.existsSync(frontendDistIndexPath)) {
    fs.writeFileSync(frontendDistIndexPath, '<!DOCTYPE html><html><body>Test</body></html>');
  }
});

/**
 * Helper to find resources by type in a CloudFormation template
 */
function findResources(template: Record<string, unknown>, resourceType: string): Record<string, unknown>[] {
  const resources = template.Resources as Record<string, { Type: string; Properties?: unknown }>;
  return Object.values(resources).filter(r => r.Type === resourceType);
}

/**
 * Helper to find a resource by type and return its properties
 */
function findResourceProperties(template: Record<string, unknown>, resourceType: string): unknown[] {
  return findResources(template, resourceType).map(r => (r as { Properties?: unknown }).Properties);
}

/**
 * Helper to find the main upload bucket
 */
function findMainBucket(template: Record<string, unknown>): Record<string, unknown> {
  const buckets = findResourceProperties(template, 'AWS::S3::Bucket');
  return buckets[0] as Record<string, unknown>;
}

describe('SecureFileDropStack', () => {
  let template: Record<string, unknown>;

  beforeAll(() => {
    const app = new cdk.App({
      context: {
        notificationEmail: 'test@example.com',
      },
    });
    const stack = new SecureFileDropStack(app, 'TestStack');

    // Synthesize and get the raw template JSON
    // This avoids CDK assertions library's overly strict cyclic dependency check
    const assembly = app.synth();
    template = assembly.getStackArtifact(stack.artifactId).template as Record<string, unknown>;
  });

  describe('S3 Bucket', () => {
    it('should create S3 bucket with encryption enabled', () => {
      const buckets = findResourceProperties(template, 'AWS::S3::Bucket');
      expect(buckets.length).toBe(1);

      const bucket = buckets[0] as Record<string, unknown>;
      expect(bucket.BucketEncryption).toBeDefined();

      const encryption = bucket.BucketEncryption as Record<string, unknown[]>;
      const sseConfig = encryption.ServerSideEncryptionConfiguration?.[0] as Record<string, unknown>;
      const sseDefault = sseConfig?.ServerSideEncryptionByDefault as Record<string, string>;
      expect(sseDefault?.SSEAlgorithm).toBe('AES256');
    });

    it('should block all public access', () => {
      const buckets = findResourceProperties(template, 'AWS::S3::Bucket');
      const bucket = buckets[0] as Record<string, unknown>;

      const publicBlock = bucket.PublicAccessBlockConfiguration as Record<string, boolean>;
      expect(publicBlock.BlockPublicAcls).toBe(true);
      expect(publicBlock.BlockPublicPolicy).toBe(true);
      expect(publicBlock.IgnorePublicAcls).toBe(true);
      expect(publicBlock.RestrictPublicBuckets).toBe(true);
    });

    it('should have lifecycle rules for incomplete multipart uploads on main bucket', () => {
      const bucket = findMainBucket(template);

      const lifecycle = bucket.LifecycleConfiguration as Record<string, unknown[]>;
      const rules = lifecycle.Rules;

      const abortRule = rules.find((r: unknown) =>
        (r as Record<string, unknown>).Id === 'AbortIncompleteMultipart'
      ) as Record<string, unknown>;

      expect(abortRule).toBeDefined();
      const abort = abortRule.AbortIncompleteMultipartUpload as Record<string, number>;
      expect(abort.DaysAfterInitiation).toBe(RETENTION_DAYS);
    });

    it('should have Intelligent-Tiering lifecycle rule for uploads', () => {
      const bucket = findMainBucket(template);

      const lifecycle = bucket.LifecycleConfiguration as Record<string, unknown[]>;
      const rules = lifecycle.Rules;

      const tieringRule = rules.find((r: unknown) =>
        (r as Record<string, unknown>).Id === 'IntelligentTieringForUploads'
      ) as Record<string, unknown>;

      expect(tieringRule).toBeDefined();
      expect(tieringRule.Prefix).toBe('uploads/');

      const transitions = tieringRule.Transitions as Array<Record<string, unknown>>;
      expect(transitions[0].StorageClass).toBe('INTELLIGENT_TIERING');
      expect(transitions[0].TransitionInDays).toBe(30);
    });

    it('should have CORS configuration for presigned uploads', () => {
      const bucket = findMainBucket(template);

      const cors = bucket.CorsConfiguration as Record<string, unknown[]>;
      const rule = cors.CorsRules[0] as Record<string, unknown>;

      expect(rule.AllowedMethods).toContain('PUT');
      expect(rule.AllowedMethods).toContain('GET');
      expect(rule.AllowedOrigins).toContain('*');
      expect(rule.ExposedHeaders).toContain('ETag');
    });

    it('should have RETAIN removal policy', () => {
      const resources = template.Resources as Record<string, { Type: string; DeletionPolicy?: string }>;
      const buckets = Object.values(resources).filter(r => r.Type === 'AWS::S3::Bucket');

      expect(buckets.length).toBe(1);
      expect(buckets[0].DeletionPolicy).toBe('Retain');
    });
  });

  describe('Lambda Function', () => {
    it('should use Node.js 22.x runtime', () => {
      const lambdas = findResourceProperties(template, 'AWS::Lambda::Function');
      const lambda = lambdas[0] as Record<string, unknown>;
      expect(lambda.Runtime).toBe('nodejs22.x');
    });

    it('should NOT have reserved concurrency by default (requires quota >= 110)', () => {
      // Reserved concurrency is optional - new AWS accounts have only 10 concurrent execution quota
      // and AWS requires 100 unreserved, so we don't set it by default
      const lambdas = findResourceProperties(template, 'AWS::Lambda::Function');
      const lambda = lambdas[0] as Record<string, unknown>;
      expect(lambda.ReservedConcurrentExecutions).toBeUndefined();
    });

    it('should have appropriate timeout (30 seconds)', () => {
      const lambdas = findResourceProperties(template, 'AWS::Lambda::Function');
      const lambda = lambdas[0] as Record<string, unknown>;
      expect(lambda.Timeout).toBe(30);
    });

    it('should have appropriate memory (512MB)', () => {
      const lambdas = findResourceProperties(template, 'AWS::Lambda::Function');
      const lambda = lambdas[0] as Record<string, unknown>;
      expect(lambda.MemorySize).toBe(512);
    });

    it('should have required environment variables', () => {
      const lambdas = findResourceProperties(template, 'AWS::Lambda::Function');
      const lambda = lambdas[0] as Record<string, unknown>;
      const env = lambda.Environment as Record<string, Record<string, unknown>>;
      const vars = env.Variables;

      expect(vars.BUCKET_NAME).toBeDefined();
      expect(vars.SNS_TOPIC_ARN).toBeDefined();
    });
  });

  describe('Lambda Function URL', () => {
    it('should create a function URL with no auth', () => {
      const urls = findResourceProperties(template, 'AWS::Lambda::Url');
      expect(urls.length).toBeGreaterThan(0);

      const url = urls[0] as Record<string, unknown>;
      expect(url.AuthType).toBe('NONE');
    });

    it('should have CORS configured', () => {
      const urls = findResourceProperties(template, 'AWS::Lambda::Url');
      const url = urls[0] as Record<string, unknown>;
      const cors = url.Cors as Record<string, unknown>;

      expect(cors.AllowMethods).toContain('GET');
      expect(cors.AllowMethods).toContain('POST');
      expect(cors.AllowOrigins).toContain('*');
    });
  });

  describe('SNS Topic', () => {
    it('should create an SNS topic', () => {
      const topics = findResourceProperties(template, 'AWS::SNS::Topic');
      expect(topics.length).toBeGreaterThan(0);
      // Note: Topic name is auto-generated by CloudFormation to prevent naming conflicts
    });

    it('should have email subscription', () => {
      const subs = findResourceProperties(template, 'AWS::SNS::Subscription');
      expect(subs.length).toBeGreaterThan(0);

      const sub = subs[0] as Record<string, string>;
      expect(sub.Protocol).toBe('email');
      expect(sub.Endpoint).toBe('test@example.com');
    });
  });

  describe('CloudFront Distribution', () => {
    it('should create a CloudFront distribution', () => {
      const dists = findResources(template, 'AWS::CloudFront::Distribution');
      expect(dists.length).toBe(1);
    });

    it('should have HTTPS redirect enabled', () => {
      const dists = findResourceProperties(template, 'AWS::CloudFront::Distribution');
      const dist = dists[0] as Record<string, Record<string, unknown>>;
      const config = dist.DistributionConfig;
      const defaultBehavior = config.DefaultCacheBehavior as Record<string, string>;
      expect(defaultBehavior.ViewerProtocolPolicy).toBe('redirect-to-https');
    });

    it('should have default root object set', () => {
      const dists = findResourceProperties(template, 'AWS::CloudFront::Distribution');
      const dist = dists[0] as Record<string, Record<string, unknown>>;
      expect(dist.DistributionConfig.DefaultRootObject).toBe('index.html');
    });

    it('should have custom error response for SPA routing', () => {
      const dists = findResourceProperties(template, 'AWS::CloudFront::Distribution');
      const dist = dists[0] as Record<string, Record<string, unknown>>;
      const errors = dist.DistributionConfig.CustomErrorResponses as Array<Record<string, unknown>>;

      const error404 = errors.find(e => e.ErrorCode === 404);
      expect(error404).toBeDefined();
      expect(error404?.ResponseCode).toBe(200);
      expect(error404?.ResponsePagePath).toBe('/index.html');
    });
  });

  describe('CloudWatch Alarms', () => {
    // Note: Alarm names are auto-generated by CloudFormation to prevent naming conflicts
    // We identify alarms by their MetricName instead

    it('should create Lambda error alarm', () => {
      const alarms = findResourceProperties(template, 'AWS::CloudWatch::Alarm');
      const errorAlarm = alarms.find(a =>
        (a as Record<string, string>).MetricName === 'Errors'
      ) as Record<string, unknown>;

      expect(errorAlarm).toBeDefined();
      expect(errorAlarm.Threshold).toBe(5);
      expect(errorAlarm.EvaluationPeriods).toBe(1);
    });

    it('should create Lambda throttle alarm', () => {
      const alarms = findResourceProperties(template, 'AWS::CloudWatch::Alarm');
      const throttleAlarm = alarms.find(a =>
        (a as Record<string, string>).MetricName === 'Throttles'
      ) as Record<string, unknown>;

      expect(throttleAlarm).toBeDefined();
      expect(throttleAlarm.Threshold).toBe(1);
    });

    it('should create Lambda duration alarm', () => {
      const alarms = findResourceProperties(template, 'AWS::CloudWatch::Alarm');
      const durationAlarm = alarms.find(a =>
        (a as Record<string, string>).MetricName === 'Duration'
      ) as Record<string, unknown>;

      expect(durationAlarm).toBeDefined();
      expect(durationAlarm.Threshold).toBe(25000);
      expect(durationAlarm.EvaluationPeriods).toBe(2);
    });

    it('should create CloudFront 5xx alarm', () => {
      const alarms = findResourceProperties(template, 'AWS::CloudWatch::Alarm');
      const cfAlarm = alarms.find(a =>
        (a as Record<string, string>).MetricName === 'TotalErrorRate'
      ) as Record<string, unknown>;

      expect(cfAlarm).toBeDefined();
      expect(cfAlarm.Threshold).toBe(5);
      expect(cfAlarm.EvaluationPeriods).toBe(2);
    });

    it('should have alarms connected to SNS topic', () => {
      const alarms = findResourceProperties(template, 'AWS::CloudWatch::Alarm');
      alarms.forEach(alarm => {
        const a = alarm as Record<string, unknown>;
        expect(a.AlarmActions).toBeDefined();
        expect(Array.isArray(a.AlarmActions)).toBe(true);
      });
    });
  });

  describe('IAM Permissions', () => {
    it('should grant Lambda S3 read/write permissions', () => {
      const policies = findResourceProperties(template, 'AWS::IAM::Policy');
      const policyDocs = policies.map(p =>
        (p as Record<string, Record<string, unknown>>).PolicyDocument
      );

      const hasS3Permissions = policyDocs.some(doc => {
        const statements = doc.Statement as Array<Record<string, unknown>>;
        return statements.some(s => {
          const actions = s.Action as string[];
          return Array.isArray(actions) && (
            actions.includes('s3:GetObject*') ||
            actions.includes('s3:PutObject*')
          );
        });
      });

      expect(hasS3Permissions).toBe(true);
    });

    it('should grant Lambda multipart upload permissions', () => {
      const policies = findResourceProperties(template, 'AWS::IAM::Policy');
      const policyDocs = policies.map(p =>
        (p as Record<string, Record<string, unknown>>).PolicyDocument
      );

      const hasMultipartPermissions = policyDocs.some(doc => {
        const statements = doc.Statement as Array<Record<string, unknown>>;
        return statements.some(s => {
          const actions = s.Action as string[];
          return Array.isArray(actions) &&
            actions.includes('s3:CreateMultipartUpload') &&
            actions.includes('s3:CompleteMultipartUpload');
        });
      });

      expect(hasMultipartPermissions).toBe(true);
    });

    it('should grant Lambda SNS publish permissions', () => {
      const policies = findResourceProperties(template, 'AWS::IAM::Policy');
      const policyDocs = policies.map(p =>
        (p as Record<string, Record<string, unknown>>).PolicyDocument
      );

      const hasSNSPermissions = policyDocs.some(doc => {
        const statements = doc.Statement as Array<Record<string, unknown>>;
        return statements.some(s => s.Action === 'sns:Publish');
      });

      expect(hasSNSPermissions).toBe(true);
    });
  });

  describe('Stack Outputs', () => {
    it('should output WebsiteUrl', () => {
      const outputs = template.Outputs as Record<string, Record<string, unknown>>;
      expect(outputs.WebsiteUrl).toBeDefined();
      expect(outputs.WebsiteUrl.Description).toBe('CloudFront URL for the website');
    });

    it('should output LambdaFunctionUrl', () => {
      const outputs = template.Outputs as Record<string, Record<string, unknown>>;
      expect(outputs.LambdaFunctionUrl).toBeDefined();
      expect(outputs.LambdaFunctionUrl.Description).toBe('Lambda Function URL (direct access, bypasses CloudFront)');
    });

    it('should output BucketName', () => {
      const outputs = template.Outputs as Record<string, Record<string, unknown>>;
      expect(outputs.BucketName).toBeDefined();
      expect(outputs.BucketName.Description).toBe('S3 bucket name');
    });

    it('should output SnsTopicArn', () => {
      const outputs = template.Outputs as Record<string, Record<string, unknown>>;
      expect(outputs.SnsTopicArn).toBeDefined();
      expect(outputs.SnsTopicArn.Description).toBe('SNS Topic ARN for notifications');
    });

    it('should output CloudFrontDistributionId', () => {
      const outputs = template.Outputs as Record<string, Record<string, unknown>>;
      expect(outputs.CloudFrontDistributionId).toBeDefined();
      expect(outputs.CloudFrontDistributionId.Description).toBe('CloudFront distribution ID (for cache invalidation)');
    });
  });

  describe('Security Controls', () => {
    it('should have Origin Access Control for S3', () => {
      const oacs = findResources(template, 'AWS::CloudFront::OriginAccessControl');
      expect(oacs.length).toBe(1);
    });

    it('should enforce SSL on S3 bucket', () => {
      const policies = findResourceProperties(template, 'AWS::S3::BucketPolicy');

      const hasSSLPolicy = policies.some(policy => {
        const doc = (policy as Record<string, Record<string, unknown>>).PolicyDocument;
        const statements = doc.Statement as Array<Record<string, unknown>>;
        return statements.some(s => {
          const condition = s.Condition as Record<string, Record<string, string>>;
          return s.Effect === 'Deny' &&
            condition?.Bool?.['aws:SecureTransport'] === 'false';
        });
      });

      expect(hasSSLPolicy).toBe(true);
    });
  });
});

describe('SecureFileDropStack - Context Validation', () => {
  it('should throw error when notificationEmail is not provided', () => {
    const app = new cdk.App();

    expect(() => {
      new SecureFileDropStack(app, 'TestStackNoEmail');
    }).toThrow('notificationEmail context parameter is required');
  });

  it('should create stack successfully with required context', () => {
    const app = new cdk.App({
      context: {
        notificationEmail: 'valid@example.com',
      },
    });

    expect(() => {
      new SecureFileDropStack(app, 'TestStackValid');
    }).not.toThrow();
  });
});
